[package]
name = "xray-tui-core"
version.workspace = true
edition.workspace = true


[features]
default = ["quic-ping"]
quic-ping = ["dep:quinn", "dep:rustls"]
[dependencies]
# ============ Serialization ============
serde.workspace = true
serde_json.workspace = true

yaml-rust2.workspace = true
# ============ Error Handling ============
thiserror.workspace = true

# ============ Networking ============
reqwest.workspace = true
reqwest.features = ["socks", "stream", "json"]

# ============ Config & Filesystem ============
dirs.workspace = true

# ============ Async Runtime & I/O ============
tokio.workspace = true
tokio.features = ["process", "signal", "sync", "fs", "time", "io-util", "rt", "rt-multi-thread", "net"]
futures-util.workspace = true

# ============ Protocol ============
tonic = "0.14"
semver = { version = "1.0", features = ["std"] }
async-trait = "0.1"
prost = "0.14"
quinn = { version = "0.11", optional = true }
rustls = { workspace = true, optional = true, features = ["tls12", "logging", "aws_lc_rs"] }
tonic-prost = "0.14"

# ============ Build & Archiving ============
zip = "8.6"
flate2 = "1.1"
tar = "0.4"

# ============ Internal ============
xray-tui-db = { path = "../xray-tui-db" }
xray-tui-proto = { path = "../xray-tui-proto" }

# ============ Logging ============
tracing.workspace = true
libc = "0.2"
tempfile = "3"

# ============ Persistent Log Storage ============
heed = { version = "0.22" }
postcard = { version = "1", features = ["alloc"] }
byteorder = "1"

[build-dependencies]
tonic-prost-build = "0.14"

[dev-dependencies]
xray-tui-config = { path = "../xray-tui-config" }
toasty = "0.9"
jiff.workspace = true