[workspace]
resolver = "3"

members = ["crates/*"]

[workspace.package]
version = "0.1.0"

edition = "2024"
rust-version = "1.96.0"

readme = "README.md"
license = "MIT"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -2 }

missing_errors_doc = "allow"
missing_panics_doc = "allow"
too_many_arguments = "allow"
too_many_lines = "allow"

[workspace.dependencies]
# ============ Async Runtime & I/O ============
tokio = { version = "1.52" }
futures-util = { version = "0.3", default-features = false, features = ["std"] }

# ============ Serialization ============
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

# ============ Error Handling ============
thiserror = { version = "^2.0.18" }

# ============ Networking ============
reqwest = { version = "^0.13.4", default-features = false, features = ["rustls"] }

# ============ Config & Filesystem ============
dirs = { version = "^6.0.0" }

# ============ Text / Search / Hash ============
uuid = { version = "^1.23.4", features = ["v4"] }

# ============ Logging ============
tracing = { version = "0.1" }
# ============ Time / Duration Parsing ============
humantime = "2.1"
