[package]
name = "xray-tui-config"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
dirs = "6"
base64 = "0.22"
url = "2"
xray-tui-core = { path = "../xray-tui-core" }
xray-tui-db = { path = "../xray-tui-db" }
uuid = { version = "1", features = ["v4"] }
