[package]
name = "xray-tui-route"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# ============ Serialization ============
serde.workspace = true
serde_json.workspace = true

# ============ Error Handling ============
thiserror.workspace = true

# ============ Text / Search / Hash ============
aho-corasick.workspace = true
regex = "1.11"
tokio = { workspace = true, features = ["sync"] }


# ============ Time / Duration Parsing ============
jiff.workspace = true

[features]
default = []
dns = ["dep:xray-tui-dns"]
geoip = ["dep:xray-tui-geoip"]

[dependencies.xray-tui-dns]
version = "0.1"
path = "../xray-tui-dns"
optional = true

[dependencies.xray-tui-geoip]
version = "0.1"
path = "../xray-tui-geoip"
optional = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }

[lints]
workspace = true
