#!/usr/bin/env python3
"""Generates catalog_data.rs from the frozen ja4db-export CSV snapshot.

Cleaning rules (per the design spec):
- keep rows whose ja4_fingerprint matches ^t1[0-3] AND have an identifiable
  application: non-empty `application` OR a parseable user_agent_string;
- parse UA -> (browser, major, os, device); unparseable rows dropped;
- dedupe on (ja4, browser, major, os, device); sum observation_count.
"""
import csv
import re
import sys
from collections import OrderedDict

CSV_PATH = "thirdparty/ja4db-export/csv/all_records.csv"
OUT_PATH = "crates/xray-tui-tls/src/fingerprints/catalog/catalog_data.rs"

JA4_RE = re.compile(r"^t1[0-3][a-z]")
# Rust-string-safe shape: lowercase alnum segments, 2 or 3 parts.
JA4_STRICT_RE = re.compile(r"^t1[0-3][a-z0-9]+(?:_[a-z0-9]+){1,2}$")
BROWSERS = [
    ("edg", "edge"), ("Edg", "edge"),
    ("Samsung", "samsung"), ("Firefox", "firefox"), ("Chrome", "chrome"),
    ("Safari", "safari"), ("Opera", "opera"), ("OPR", "opera"),
]
OS_PATTERNS = [
    (r"Windows NT 10\.0", "windows"), (r"Windows NT 6\.[13]", "windows"),
    (r"Windows NT 6\.[02]", "windows"), (r"Windows NT 5", "windows"),
    (r"Mac OS X|Macintosh", "macos"), (r"Android", "android"),
    (r"iPhone|iPad", "ios"), (r"Cros", "linux"), (r"X11|Linux", "linux"),
]
VERSION_RE = {
    "chrome": r"(?:Chrome|CriOS)/(\d+)\.",
    "edge": r"(?:Edge|Edg)/(\d+)\.",
    "firefox": r"Firefox/(\d+)\.",
    "safari": r"Version/(\d+)\.",
    "opera": r"(?:Opera|OPR)/(\d+)\.",
    "samsung": r"SamsungBrowser/(\d+)\.",
}


def parse_application(application):
    """Direct application field, e.g. 'Chrome 94.0'.

    Returns a 4-tuple matching parse_ua(); application-only rows carry no
    OS/device evidence, so those fields stay empty.
    """
    m = re.match(r"^(Chrome|Firefox|Safari|Edge|Brave|Opera|Samsung Internet)"
                 r"(?: ([0-9]+)(?:\.[0-9]+)?)?\s*$", application.strip())
    if not m:
        return None
    name = {"Samsung Internet": "samsung"}.get(m.group(1), m.group(1).lower())
    return name, int(m.group(2)) if m.group(2) else None, "", ""


def parse_ua(ua):
    ua = ua.strip()
    if not ua:
        return None
    browser = None
    for token, name in BROWSERS:
        if token in ua:
            browser = name
            break
    if browser is None:
        # Safari-only UAs carry no engine token besides Version/
        if "Version/" in ua and "Safari" in ua:
            browser = "safari"
        else:
            return None
    vm = re.search(VERSION_RE[browser], ua)
    version = int(vm.group(1)) if vm else None
    os_name = None
    for pat, o in OS_PATTERNS:
        if re.search(pat, ua):
            os_name = o
            break
    device = "phone" if ("iPhone" in ua or "Android" in ua and "Mobile" in ua) else (
        "tablet" if "iPad" in ua or ("Android" in ua and "Mobile" not in ua) else "desktop")
    if os_name is None:
        return None
    return browser, version, os_name, device


def main():
    rows = OrderedDict()  # key -> row dict
    dropped = kept = 0
    with open(CSV_PATH, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for r in reader:
            ja4 = (r.get("ja4_fingerprint") or "").strip()
            if not JA4_RE.match(ja4) or not JA4_STRICT_RE.match(ja4):
                continue
            parsed = parse_application(r.get("application") or "") or parse_ua(r.get("user_agent_string") or "")
            if parsed is None:
                dropped += 1
                continue
            browser, version, os_name, device = parsed
            try:
                count = int(r.get("observation_count") or "1")
            except ValueError:
                count = 1
            key = (ja4, browser, version, os_name, device)
            if key in rows:
                rows[key]["observation_count"] += count
            else:
                rows[key] = {
                    "ja4": ja4, "application": browser, "library": (r.get("library") or "").strip(),
                    "device": device, "os": os_name,
                    "user_agent": (r.get("user_agent_string") or "").strip(),
                    "verified": (r.get("verified") or "").strip() == "true",
                    "observation_count": count, "_version": version,
                }
            kept += 1

    def esc(s):
        # Drop anything a Rust string literal cannot carry verbatim
        # (stray control bytes / non-ASCII junk in the raw CSV).
        s = s.replace("\\", "\\\\").replace('"', '\\"')
        return "".join(c for c in s if 32 <= ord(c) < 127)

    lines = [
        "// GENERATED by catalog/gen.py from thirdparty/ja4db-export (frozen",
        "// snapshot 2026-05-15). Do not edit by hand; rerun the generator.",
        "/// One cleaned real-world JA4 observation.",
        "#[derive(Debug, Clone)]",
        "pub struct CatalogEntry {",
        "    pub ja4: &'static str,",
        "    pub application: &'static str,",
        "    pub library: &'static str,",
        "    pub device: &'static str,",
        "    pub os: &'static str,",
        "    pub user_agent: &'static str,",
        "    pub verified: bool,",
        "    pub observation_count: u64,",
        "}",
        "",
        "/// The cleaned catalog.",
        "pub static CATALOG: &[CatalogEntry] = &[",
    ]
    for row in rows.values():
        lines.append(
            "    CatalogEntry {{ ja4: \"{ja4}\", application: \"{app}\", "
            "library: \"{lib}\", device: \"{dev}\", os: \"{os}\", "
            "user_agent: \"{ua}\", verified: {ver}, observation_count: {cnt} }},".format(
                ja4=esc(row["ja4"]), app=esc(row["application"]), lib=esc(row["library"]),
                dev=esc(row["device"]), os=esc(row["os"]), ua=esc(row["user_agent"][:200]),
                ver="true" if row["verified"] else "false",
                cnt=row["observation_count"],
            ))
    lines.append("];")
    with open(OUT_PATH, "w", encoding="utf-8") as out:
        out.write("\n".join(lines) + "\n")
    print(f"kept {len(rows)} unique entries ({kept} rows merged, {dropped} dropped)", file=sys.stderr)


if __name__ == "__main__":
    main()
